### ISSUE TITLE
Generated hashCode Model breaks contract

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-swagger-coden#17]
As per [this discussion](https://groups.google.com/g/killbilling-users/c/IGhO4E4qXoY), we should modify our generator to not rely on the `Object#hashCode`.

**Comment by benweidig** [comment]
Hi,

I gave the code a quick look, and in my opinion, there are two ways to fix the issue.

**Option 1: Remove super.hashCode() from the template**

The "easiest" fix would be the simple removal of the `super.hashCode()` realted stuff in https://github.com/killbill/killbill-swagger-coden/blob/bcb2ed25a8949ba7c4d945e123b80ad91ed1252a/src/main/resources/killbill-java/pojo.mustache#L108

A more comprehensive fix would be changing `KillbillJavaGenerator#postProcessModels(Map<String, Object> objs)` to set a vendor extension to ignore `super.hashCode()` if the parent is `KillBillObject`.
But hat would create strong cohesion between the generated model class and its parent's implementation.


**Option 2: Give KillBillObject equals/hashCode**

Instead of fixing the template, maybe `KillBillObject` shouldn't expose `auditLog` as `protected` in the first place.
`KillBillObject` has a `public` getter and setter so any subclass can use those instead.
If it also provides `equals`/`hashCode`, sub-classes wouldn't need to explicitly check it and rely on a `super` call.

Such a change would also allow `KillBillObject` to add new fields without worrying about breaking any of its sub-classes.
Although that's kind of a moot point because all the code is generated...


-- 

I prefer the second option because it "feels" cleaner and doesn't bind the codegen-templates with the actual KillBillObject implementation too strongly.
But I'm happy to provide a PR for the option you prefer.

**Comment by sbrossie** [comment]
Hi Ben,

I also prefer the second approach, since KillBillObject is the base class
of most of the generated code (models), providing a default implementation
for hashCode()/equals() makes sense. Feel free to submit a PR to address
this issue.

Thanks,

Stéphane

**Comment by benweidig** [comment]
I've tried to work on the issue but ran immediately into more problems...

Giving `KillBillObject` its own `equals`/`hashCode` is easy, but the generated code still includes the `auditLog` in sub-classes.
I have not much experience with Swagger, but it looks like the KB Swagger spec doesn't define the inheritance between the different models directly and includes `auditLog` as a property to every model instead.
That's why `KillBillGenerator` has special handling if a property called `auditLog` is present, creating the parent-child relationship manually.

The Swagger spec and the generated code are at the core of everything, so changing it is kind of a no-go (for me).
At least without a deep understanding of Swagger and KillBill internals, I won't suggest it or write any kind of PR. The possible implications are too high.

So I re-evaluated the previous options, and now there are three options:

**Option 1: Remove super.hashCode() from the template**

Same as before. Remove the super call from hashCode and call it a day. Still not the best solutions compared to the others.

**Option 2: Option 2: Give KillBillObject equals/hashCode**

Add  `equals`/`hashCode` to `KillBillObject` and re-add `super.equals` to the pojo-template.
That will lead to `auditLog` to be evaluated twice in both methods, first locally then via `super`.
Feels like an ugly hack but wouldn't require any special handling.

**Option 3: Option 2 but with special handling to prevent double calls**

Not sure if it's easily doable, but there could be special handling for `equals`/`hashCode`/`toString` to ignore the inherited `protected` field `auditLog` defined via Swagger spec and call `super` instead.
As far as I saw in the code, `KillBillObject` is the only parent type, and the Swagger spec doesn't define any inheritance.
So the special handling would (hopefully) be minimal and only in the generator and the custom mustache templates.
There's already the custom generator, so the technical debt/maintainability shouldn't increase much with some explanatory comments of why/how the special handling is necessary.

** **

I didn't expect such a scope/impact of the issue, and I'm not sure what would be the best solution because of that.
But I still want to help with a PR if possible.

**Comment by sbrossie** [comment]
As often the case, things are more complex than they look. There is some work required around defining what 'equality' of these models really mean, and extra implementation work to make it happen considering this is generated code, and therefore harder to 'tune' for specific behaviors.

What does equality mean?

* Should audit logs be included: I suppose it depends if we could end up in a case where 2 different models have the same fields and yet different audit logs. Perhaps an example is to have an extra update with the same values, hence leaving the resource unchanged but with additional audit logs - of course it depends how the server has been implemented, and whether such operation would lead to an extra audit log. In any case, there are certainly arguments for both implememtations. I am personally in favor of not included audit logs, but don't have a strong opinion about it either way.

* Some resource contain fields that are only fetched when explicitely asked - e.g `Account#accountBalance`. So, if [fethcing twice the resource]( https://killbill.github.io/slate/#account-retrieve-an-account-by-its-id), one time with `accountWithBalance=true`, and one time `accountWithBalance=false`, it is likely that comparing these models will lead to a non equality, but in reality, one is just not fully populated.


Things we should strive for:
* Consistency: Currently we seem to have different behavior for different resources. The [first](https://github.com/killbill/killbill-client-java/blob/master/src/main/java/org/killbill/billing/client/model/gen/Account.java#L447) one includes audit logs, and calls `super`, and the [second](https://github.com/killbill/killbill-client-java/blob/master/src/main/java/org/killbill/billing/client/model/gen/Overdue.java#L97) does not of those.
* Contracts around `equals` and `hashCode`: If two resources are 'equal', they must have the same hashCode.
* Avoid inheritance and favor composition to avoid comparing parent v.s child object and getting inconsistent results. I think we are ok, as the only parent class is `KillBillObject` and it is `abstract`.


@benweidig Any PR that improves things along these direction is welcome.

**Comment by benweidig** [comment]
Sorry for another "wall of text"...

You're absolutely right, the real question is what "equality" actually should mean for the models.

As "just" a user of the client code, I expected `equals/hashCode` to be the "usual" object equality down to the fields because there's no documentation indicating otherwise.

I'm still quite new to the KB and I haven't thought about `Account#accountBalance` and fields that are only populated if explicitly requested.
From a purely Java point of view, `accountWithBalance=true` and `accountWithBalance=false` are *not* equal.
But as a KillBill API user, they might.

That reflects the use-case we were trying to implement.
We mirror some of the parts of some models of KillBill in our own system (for reporting, mailing etc.).
While checking an user's entitlement, we want to update our database if something has changed.
My first thought was using `hashCode` as a simple indicator.
It might not be the most stable solution because changed auditLogs could be responsible for a new `hashCode` even if the properties we're interested in haven't changed.
But the overall updates in our system would go down.

What we really need is a checksum or version number to easily identify changed objects.
Although that wouldn't solve the "not fully populated" problem... because a checksum could only represent the always populated fields, too. And we're back to the "what does equality mean?" question.
But it would make more sense for a checksum to ignore some fields like auditLog, compared to `equals`.
Another approach would be another method for comparing models, like `shallowEquals(...)` or `isSame(...)` or something along that line.
Well, if you even want to provide such functionality.
To mitigate on our end, we generate a custom hashCode/checksum with only the fields we need.

Regarding the points to strive for:

* Consistency: If a model doesn't have auditLogs, and therefore is not a subclass of `KillBillObject`, it doesn't have to call super, so it seems consistent to me.

* equals/hashCode: I concur. But without additional documentation or any other indication, it should include all fields IMO.

* Inheritance vs. Composition: Inheritance can be beneficial if designed well. But as mentioned before, I believe Swagger is making it really hard to generate the correct Java code. At least as far as I understand it after reading the documentation and related issues.

What exactly is `KillBillObject` used for?
I can't seem to find anything besides being a shared abstract class for models with auditLogs.
But I don't have all the different projects checked out, so it might be used somewhere else.

In the swagger yaml/json, the auditLogs are composed.
That's why the special handling in the generator to create the inheritance is needed.
Could the class be removed or replaced by an interface declaring the getter and setter if a shared type is needed? This way, auditLog models still share a common type, but merely thanks to the marker interface, not "real" inheritance. And the code generator wouldn't need special handling for the field.

As before, I'm not that versed in either KillBill or Swagger.
So my ideas might be not feasible, non-sense in the bigger picture, or aren't aligned with the direction of KB.
And I haven't looked at the Python templates at all and how these changes might affect them.

Creating PRs might be some work, so it would help to know which way you would prefer to go forward. If removing/replacing `KillBillObject` with an interface is a no-go for you, I don't need to create a PR in the first place.

https://github.com/killbill/killbill-client-java/pull/91 mitigates the general problem, so it would be great if it could be merged.
But not changing any additional code until another problem arises is also an option.
I'm not one of these people thinking OSS means the project has to accept every change I personally need for my special use-case.

**Comment by sbrossie** [comment]
I think we are in agreement with regard to what the issues are, so let me try to suggest 2 paths:

1. Create a PR that remove special handling for audit logs + inheritance -- your suggestion.

If you feel motivated to tackle this, and if we end up with generated code that is better as far as equals/hashCode are concerned, all good.


2. If this is too much work/too complex/does not lead to satisfying code generation, implement a simpler approach:
* models don't call `super`
* audit logs are not part of the equals/hashCode contract -- and yes, in this case we would have the generated code add a comment for this.
